baseurl = "https://acmla-acacc.ca/carto2019/"
#baseurl = "http://localhost/carto2019/public/"
author = "ACMLA-ACACC"
title = "Carto 2019"
theme = "hugof"
enableRobotsTXT = true
SectionPagesMenu = ["main"]
googleAnalytics = ""
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[Languages]

[Languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 1

[Languages.en.params]

[Languages.en.meta]
    description = "The 53rd Annual Conference of the Association of Canadian Map Libraries and Archives (ACMLA)"
    keywords = "libraries, archives, maps, cartography, data"

[Languages.en.hero]
    herotitle = ""
    herodescription = ""
    logo = "img/carto2019_logo1.png" #img/filename.png
    logoalt = ""

[Languages.en.main]
    contentOneAlert = ""
    contentOneTitle = "CARTO 2019"
    contentOneBody = "On behalf of the Executive, we are pleased to announce that McMaster University will host the 53rd annual CARTO conference of the Association of Canadian Map Libraries and Archives in Hamilton, Ontario from June 11-14, 2019."

[Languages.en.footer]
    email = "carto.conference@gmail.com"
    copy = "2019 ACMLA-ACACC"
    footlogo = "img/mcm-library_left-rev.png"
    footlogoalt = "McMaster University Library"
    footlink = "https://library.mcmaster.ca/"

#[[Languages.en.menu.main]]
#    name = "Program"
#    url = "/schedule"
#    weight = 1

#[[Languages.en.menu.main]]
#    name = "Local Information"
#    url = "/localinfo"
#    weight = 2

#[[Languages.en.menu.main]]
#    name = "Accommodations"
#    url = "/accommodations"
#    weight = 3

[[Languages.en.menu.main]]
    name = "About"
    url = "/about"
    weight = 4

[Languages.fr]
languageCode = "fr"
languageName = "Français"
weight = 2

[Languages.fr.params]

    [Languages.fr.meta]
    description = "53e colloque annuel de l’Association des cartothèques et archives cartographiques du Canada (ACACC)."

    [Languages.fr.hero]
    herotitle = ""
    herodescription = ""
    logo = "img/carto2019_logo1.png"
    logoalt = "Carto 2019 logo"

    [Languages.fr.main]
    contentOneAlert = ""
    contentOneTitle = ""
    contentOneBody = "Au nom de l'Exécutif de l'ACACC, nous sommes heureux d'annoncer le 53e CARTO congrèsannuel de l’Association des cartothèques et archives cartographiques du Canada organisé par l'Université McMaster, du 11 au 14 juin 2019, à Hamilton en Ontario."

    [Languages.fr.footer]
    email = "carto.conference@gmail.com"
    copy = "2019 ACMLA-ACACC"
    footlogo = "img/mcm-library_left-rev.png"
    footlogoalt = "McMaster University Library"
    footlink = "https://library.mcmaster.ca/"


# [[Languages.fr.menu.main]]
# name = "Programme"
# url = "/fr/schedule"
# weight = 1

# [[Languages.fr.menu.main]]
# name = "Lieu"
# url = "/fr/localinfo"
# weight = 2

# [[Languages.fr.menu.main]]
# name = "Hébergement"
# url = "/fr/accommodations"
# weight = 3

[[Languages.fr.menu.main]]
name = "À propos"
url = "/fr/about"
weight = 4
